version: '1.0.{build}'

shallow_clone: true
image: Visual Studio 2017

before_build:
  - ps: mkdir build ; cd build
  - ps: cmake .. -G "Visual Studio 15 2017"

build_script:
  - ps: cmake --build . --config Release

artifacts:
  - path: build\Release\WinFreddy.exe
    name: WinFreddy

deploy:
  release: WinFreddy v$(appveyor_build_version)
  description: 'Portable version'
  provider: GitHub
  auth_token:
    secure: FDRmppSa+8auET1jOPu6Yevbt84DHbwDSWeF0gQu7wdoRh/fUac5FVw2n2xWg702
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
